import type { Source } from '@/types';

// https://github.com/nj-lizhi
// https://testingcf.jsdelivr.net/gh/nj-lizhi/song@master/audio/list-v2.js
const prefix = 'https://testingcf.jsdelivr.net/gh/nj-lizhi/song@main/audio';

const source: Source = {
    albums: [
        {
            name: '梵高先生',
            year: 2006,
            albumId: 0,
            cover: `${prefix}/梵高先生/cover.png`,
            songs: [
                {
                    albumId: 0,
                    songId: 0,
                    name: '你离开了南京，从此没有人和我说话',
                    url: `${prefix}/梵高先生/你离开了南京，从此没有人和我说话.mp3`,
                },
                {
                    albumId: 0,
                    songId: 1,
                    name: '董卓瑶',
                    url: `${prefix}/梵高先生/董卓瑶.mp3`,
                },
                {
                    albumId: 0,
                    songId: 2,
                    name: '春末的南方城市',
                    url: `${prefix}/梵高先生/春末的南方城市.mp3`,
                },
                {
                    albumId: 0,
                    songId: 3,
                    name: '来了',
                    url: `${prefix}/梵高先生/来了.mp3`,
                },
                {
                    albumId: 0,
                    songId: 4,
                    name: '广场',
                    url: `${prefix}/梵高先生/广场.mp3`,
                },
                {
                    albumId: 0,
                    songId: 5,
                    name: '暧昧',
                    url: `${prefix}/梵高先生/暧昧.mp3`,
                },
                {
                    albumId: 0,
                    songId: 6,
                    name: '梵高先生',
                    url: `${prefix}/梵高先生/梵高先生.mp3`,
                },
                {
                    albumId: 0,
                    songId: 7,
                    name: '想起了她',
                    url: `${prefix}/梵高先生/想起了她.mp3`,
                },
                {
                    albumId: 0,
                    songId: 8,
                    name: '斜',
                    url: `${prefix}/梵高先生/斜.mp3`,
                },
            ],
        },
        {
            name: '被禁忌的游戏',
            year: 2006,
            albumId: 1,
            cover: `${prefix}/被禁忌的游戏/cover.png`,
            songs: [
                {
                    albumId: 1,
                    songId: 9,
                    name: '黑色信封',
                    url: `${prefix}/被禁忌的游戏/黑色信封.mp3`,
                },
                {
                    albumId: 1,
                    songId: 10,
                    name: '阿兰',
                    url: `${prefix}/被禁忌的游戏/阿兰.mp3`,
                },
                {
                    albumId: 1,
                    songId: 11,
                    name: '离婚',
                    url: `${prefix}/被禁忌的游戏/离婚.mp3`,
                },
                {
                    albumId: 1,
                    songId: 12,
                    name: '欢愉',
                    url: `${prefix}/被禁忌的游戏/欢愉.mp3`,
                },
                {
                    albumId: 1,
                    songId: 13,
                    name: '卡夫卡',
                    url: `${prefix}/被禁忌的游戏/卡夫卡.mp3`,
                },
                {
                    albumId: 1,
                    songId: 14,
                    name: '被禁忌的游戏',
                    url: `${prefix}/被禁忌的游戏/被禁忌的游戏.mp3`,
                },
                {
                    albumId: 1,
                    songId: 15,
                    name: '罗庄的冬天',
                    url: `${prefix}/被禁忌的游戏/罗庄的冬天.mp3`,
                },
                {
                    albumId: 1,
                    songId: 16,
                    name: '红色气球',
                    url: `${prefix}/被禁忌的游戏/红色气球.mp3`,
                },
            ],
        },
        {
            name: '工体东路没有人',
            year: 2009,
            albumId: 2,
            cover: `${prefix}/工体东路没有人/cover.png`,
            songs: [
                {
                    albumId: 2,
                    songId: 17,
                    name: '被禁忌的游戏',
                    url: `${prefix}/工体东路没有人/被禁忌的游戏.mp3`,
                },
                {
                    albumId: 2,
                    songId: 18,
                    name: '和你在一起',
                    url: `${prefix}/工体东路没有人/和你在一起.mp3`,
                },
                {
                    albumId: 2,
                    songId: 19,
                    name: '来了',
                    url: `${prefix}/工体东路没有人/来了.mp3`,
                },
                {
                    albumId: 2,
                    songId: 20,
                    name: '卡夫卡',
                    url: `${prefix}/工体东路没有人/卡夫卡.mp3`,
                },
                {
                    albumId: 2,
                    songId: 21,
                    name: '黑色信封',
                    url: `${prefix}/工体东路没有人/黑色信封.mp3`,
                },
                {
                    albumId: 2,
                    songId: 22,
                    name: '阿兰',
                    url: `${prefix}/工体东路没有人/阿兰.mp3`,
                },
                {
                    albumId: 2,
                    songId: 23,
                    name: '春末的南方城市',
                    url: `${prefix}/工体东路没有人/春末的南方城市.mp3`,
                },
                {
                    albumId: 2,
                    songId: 24,
                    name: '他们',
                    url: `${prefix}/工体东路没有人/他们.mp3`,
                },
                {
                    albumId: 2,
                    songId: 25,
                    name: '暧昧',
                    url: `${prefix}/工体东路没有人/暧昧.mp3`,
                },
                {
                    albumId: 2,
                    songId: 26,
                    name: '九月',
                    url: `${prefix}/工体东路没有人/九月.mp3`,
                },
                {
                    albumId: 2,
                    songId: 27,
                    name: '这个世界会好吗',
                    url: `${prefix}/工体东路没有人/这个世界会好吗.mp3`,
                },
                {
                    albumId: 2,
                    songId: 28,
                    name: '红色气球',
                    url: `${prefix}/工体东路没有人/红色气球.mp3`,
                },
                {
                    albumId: 2,
                    songId: 29,
                    name: '月亮代表我的心',
                    url: `${prefix}/工体东路没有人/月亮代表我的心.mp3`,
                },
                {
                    albumId: 2,
                    songId: 30,
                    name: '董卓瑶',
                    url: `${prefix}/工体东路没有人/董卓瑶.mp3`,
                },
                {
                    albumId: 2,
                    songId: 31,
                    name: '青春',
                    url: `${prefix}/工体东路没有人/青春.mp3`,
                },
                {
                    albumId: 2,
                    songId: 32,
                    name: '想起了他',
                    url: `${prefix}/工体东路没有人/想起了他.mp3`,
                },
            ],
        },
        {
            name: '我爱南京',
            year: 2009,
            albumId: 3,
            cover: `${prefix}/我爱南京/cover.png`,
            songs: [
                {
                    albumId: 3,
                    songId: 33,
                    name: '意味',
                    url: `${prefix}/我爱南京/意味.mp3`,
                },
                {
                    albumId: 3,
                    songId: 34,
                    name: '苍井空',
                    url: `${prefix}/我爱南京/苍井空.mp3`,
                },
                {
                    albumId: 3,
                    songId: 35,
                    name: '结婚（老狼 万晓利 李志）',
                    url: `${prefix}/我爱南京/结婚.mp3`,
                },
                {
                    albumId: 3,
                    songId: 36,
                    name: '鸵鸟',
                    url: `${prefix}/我爱南京/鸵鸟.mp3`,
                },
                {
                    albumId: 3,
                    songId: 37,
                    name: '天空之城',
                    url: `${prefix}/我爱南京/天空之城.mp3`,
                },
                {
                    albumId: 3,
                    songId: 38,
                    name: '倒影',
                    url: `${prefix}/我爱南京/倒影.mp3`,
                },
                {
                    albumId: 3,
                    songId: 39,
                    name: '爱',
                    url: `${prefix}/我爱南京/爱.mp3`,
                },
                {
                    albumId: 3,
                    songId: 40,
                    name: '家乡',
                    url: `${prefix}/我爱南京/家乡.mp3`,
                },
                {
                    albumId: 3,
                    songId: 41,
                    name: '1990年的春天',
                    url: `${prefix}/我爱南京/1990年的春天.mp3`,
                },
                {
                    albumId: 3,
                    songId: 42,
                    name: '冬妮娅-献给成都',
                    url: `${prefix}/我爱南京/冬妮娅.mp3`,
                },
                {
                    albumId: 3,
                    songId: 43,
                    name: '听妈妈讲那过去的事情（汤臣 蔡文昊 李志）',
                    url: `${prefix}/我爱南京/听妈妈讲那过去的事情.mp3`,
                },
                {
                    albumId: 3,
                    songId: 44,
                    name: '美丽的梭罗河',
                    url: `${prefix}/我爱南京/美丽的梭罗河.mp3`,
                },
                {
                    albumId: 3,
                    songId: 45,
                    name: '米店',
                    url: `${prefix}/我爱南京/米店.mp3`,
                },
                {
                    albumId: 3,
                    songId: 46,
                    name: '思念观世音',
                    url: `${prefix}/我爱南京/思念观世音.mp3`,
                },
                {
                    albumId: 3,
                    songId: 47,
                    name: '在那遥远的地方',
                    url: `${prefix}/我爱南京/在那遥远的地方.mp3`,
                },
                {
                    albumId: 3,
                    songId: 48,
                    name: '再见',
                    url: `${prefix}/我爱南京/再见.mp3`,
                },
            ],
        },
        {
            name: '二零零九年十月十六日事件',
            year: 2010,
            albumId: 4,
            cover: `${prefix}/二零零九年十月十六日事件/cover.png`,
            songs: [
                {
                    albumId: 12,
                    songId: 49,
                    name: '黑色信封',
                    url: `${prefix}/二零零九年十月十六日事件/黑色信封.mp3`,
                },
                {
                    albumId: 12,
                    songId: 50,
                    name: '董卓瑶',
                    url: `${prefix}/二零零九年十月十六日事件/董卓瑶.mp3`,
                },
                {
                    albumId: 12,
                    songId: 51,
                    name: '春末的南方城市',
                    url: `${prefix}/二零零九年十月十六日事件/春末的南方城市.mp3`,
                },
                {
                    albumId: 12,
                    songId: 52,
                    name: '来了',
                    url: `${prefix}/二零零九年十月十六日事件/来了.mp3`,
                },
                {
                    albumId: 12,
                    songId: 53,
                    name: '广场',
                    url: `${prefix}/二零零九年十月十六日事件/广场.mp3`,
                },
                {
                    albumId: 12,
                    songId: 54,
                    name: '青春',
                    url: `${prefix}/二零零九年十月十六日事件/青春.mp3`,
                },
                {
                    albumId: 12,
                    songId: 55,
                    name: '他们',
                    url: `${prefix}/二零零九年十月十六日事件/他们.mp3`,
                },
                {
                    albumId: 12,
                    songId: 56,
                    name: '被禁忌的游戏',
                    url: `${prefix}/二零零九年十月十六日事件/被禁忌的游戏.mp3`,
                },
                {
                    albumId: 12,
                    songId: 57,
                    name: '这个世界会好吗',
                    url: `${prefix}/二零零九年十月十六日事件/这个世界会好吗.mp3`,
                },
                {
                    albumId: 12,
                    songId: 58,
                    name: '妈妈',
                    url: `${prefix}/二零零九年十月十六日事件/妈妈.mp3`,
                },
                {
                    albumId: 12,
                    songId: 59,
                    name: '听妈妈讲过去的事情',
                    url: `${prefix}/二零零九年十月十六日事件/听妈妈讲过去的事情.mp3`,
                },
                {
                    albumId: 12,
                    songId: 60,
                    name: '陀螺',
                    url: `${prefix}/二零零九年十月十六日事件/陀螺.mp3`,
                },
                {
                    albumId: 12,
                    songId: 61,
                    name: '鸟语',
                    url: `${prefix}/二零零九年十月十六日事件/鸟语.mp3`,
                },
                {
                    albumId: 12,
                    songId: 62,
                    name: '狐狸',
                    url: `${prefix}/二零零九年十月十六日事件/狐狸.mp3`,
                },
                {
                    albumId: 12,
                    songId: 63,
                    name: '达摩流浪者',
                    url: `${prefix}/二零零九年十月十六日事件/达摩流浪者.mp3`,
                },
                {
                    albumId: 12,
                    songId: 64,
                    name: '结婚',
                    url: `${prefix}/二零零九年十月十六日事件/结婚.mp3`,
                },
                {
                    albumId: 12,
                    songId: 65,
                    name: '来自我心',
                    url: `${prefix}/二零零九年十月十六日事件/来自我心.mp3`,
                },
                {
                    albumId: 12,
                    songId: 66,
                    name: '虎口脱险',
                    url: `${prefix}/二零零九年十月十六日事件/虎口脱险.mp3`,
                },
                {
                    albumId: 12,
                    songId: 67,
                    name: '恋恋风尘',
                    url: `${prefix}/二零零九年十月十六日事件/恋恋风尘.mp3`,
                },
                {
                    albumId: 12,
                    songId: 68,
                    name: '倒影',
                    url: `${prefix}/二零零九年十月十六日事件/倒影.mp3`,
                },
                {
                    albumId: 12,
                    songId: 69,
                    name: '鸵鸟',
                    url: `${prefix}/二零零九年十月十六日事件/鸵鸟.mp3`,
                },
                {
                    albumId: 12,
                    songId: 70,
                    name: '天空之城',
                    url: `${prefix}/二零零九年十月十六日事件/天空之城.mp3`,
                },
                {
                    albumId: 12,
                    songId: 71,
                    name: '苍井空',
                    url: `${prefix}/二零零九年十月十六日事件/苍井空.mp3`,
                },
                {
                    albumId: 12,
                    songId: 72,
                    name: '意味',
                    url: `${prefix}/二零零九年十月十六日事件/意味.mp3`,
                },
                {
                    albumId: 12,
                    songId: 73,
                    name: '家乡',
                    url: `${prefix}/二零零九年十月十六日事件/家乡.mp3`,
                },
                {
                    albumId: 12,
                    songId: 74,
                    name: '冬妮娅',
                    url: `${prefix}/二零零九年十月十六日事件/冬妮娅.mp3`,
                },
            ],
        },
        {
            name: '你好，郑州',
            year: 2010,
            albumId: 5,
            cover: `${prefix}/你好，郑州/cover.png`,
            songs: [
                {
                    albumId: 4,
                    songId: 75,
                    name: '墙上的向日葵',
                    url: `${prefix}/你好，郑州/墙上的向日葵.mp3`,
                },
                {
                    albumId: 4,
                    songId: 76,
                    name: '铅笔',
                    url: `${prefix}/你好，郑州/铅笔.mp3`,
                },
                {
                    albumId: 4,
                    songId: 77,
                    name: '关于郑州的记忆',
                    url: `${prefix}/你好，郑州/关于郑州的记忆.mp3`,
                },
                {
                    albumId: 4,
                    songId: 78,
                    name: '忽然',
                    url: `${prefix}/你好，郑州/忽然.mp3`,
                },
                {
                    albumId: 4,
                    songId: 79,
                    name: '秋天的老狼',
                    url: `${prefix}/你好，郑州/秋天的老狼.mp3`,
                },
                {
                    albumId: 4,
                    songId: 80,
                    name: '带亲',
                    url: `${prefix}/你好，郑州/带亲.mp3`,
                },
                {
                    albumId: 4,
                    songId: 81,
                    name: '她',
                    url: `${prefix}/你好，郑州/她.mp3`,
                },
                {
                    albumId: 4,
                    songId: 82,
                    name: '路',
                    url: `${prefix}/你好，郑州/路.mp3`,
                },
                {
                    albumId: 4,
                    songId: 83,
                    name: '夜',
                    url: `${prefix}/你好，郑州/夜.mp3`,
                },
                {
                    albumId: 4,
                    songId: 84,
                    name: '铅笔(吉松浩版)',
                    url: `${prefix}/你好，郑州/铅笔(吉松浩版).mp3`,
                },
            ],
        },
        {
            name: 'IMAGINE 2011',
            year: 2011,
            albumId: 6,
            cover: `${prefix}/Imagine-2011/cover.png`,
            songs: [
                {
                    albumId: 5,
                    songId: 85,
                    name: '青春',
                    url: `${prefix}/Imagine-2011/青春.mp3`,
                },
                {
                    albumId: 5,
                    songId: 86,
                    name: '离婚',
                    url: `${prefix}/Imagine-2011/离婚.mp3`,
                },
                {
                    albumId: 5,
                    songId: 87,
                    name: '我们不能失去信仰',
                    url: `${prefix}/Imagine-2011/我们不能失去信仰.mp3`,
                },
                {
                    albumId: 5,
                    songId: 88,
                    name: '喀纳斯',
                    url: `${prefix}/Imagine-2011/喀纳斯.mp3`,
                },
                {
                    albumId: 5,
                    songId: 89,
                    name: '天空之城',
                    url: `${prefix}/Imagine-2011/天空之城.mp3`,
                },
                {
                    albumId: 5,
                    songId: 90,
                    name: '苍井空',
                    url: `${prefix}/Imagine-2011/苍井空.mp3`,
                },
                {
                    albumId: 5,
                    songId: 91,
                    name: '关于郑州的记忆',
                    url: `${prefix}/Imagine-2011/关于郑州的记忆.mp3`,
                },
                {
                    albumId: 5,
                    songId: 92,
                    name: '海的女儿',
                    url: `${prefix}/Imagine-2011/海的女儿.mp3`,
                },
                {
                    albumId: 5,
                    songId: 93,
                    name: '她',
                    url: `${prefix}/Imagine-2011/她.mp3`,
                },
                {
                    albumId: 5,
                    songId: 94,
                    name: '家乡',
                    url: `${prefix}/Imagine-2011/家乡.mp3`,
                },
                {
                    albumId: 5,
                    songId: 95,
                    name: '结婚',
                    url: `${prefix}/Imagine-2011/结婚.mp3`,
                },
                {
                    albumId: 5,
                    songId: 96,
                    name: '红色气球',
                    url: `${prefix}/Imagine-2011/红色气球.mp3`,
                },
                {
                    albumId: 5,
                    songId: 97,
                    name: '被禁忌的游戏',
                    url: `${prefix}/Imagine-2011/被禁忌的游戏.mp3`,
                },
                {
                    albumId: 5,
                    songId: 98,
                    name: '寻找',
                    url: `${prefix}/Imagine-2011/寻找.mp3`,
                },
                {
                    albumId: 5,
                    songId: 99,
                    name: '斜',
                    url: `${prefix}/Imagine-2011/斜.mp3`,
                },
                {
                    albumId: 5,
                    songId: 100,
                    name: '和你在一起',
                    url: `${prefix}/Imagine-2011/和你在一起.mp3`,
                },
                {
                    albumId: 5,
                    songId: 101,
                    name: '门',
                    url: `${prefix}/Imagine-2011/门.mp3`,
                },
                {
                    albumId: 5,
                    songId: 102,
                    name: '尽头',
                    url: `${prefix}/Imagine-2011/尽头.mp3`,
                },
                {
                    albumId: 5,
                    songId: 103,
                    name: '女神',
                    url: `${prefix}/Imagine-2011/女神.mp3`,
                },
                {
                    albumId: 5,
                    songId: 104,
                    name: '杭州',
                    url: `${prefix}/Imagine-2011/杭州.mp3`,
                },
                {
                    albumId: 5,
                    songId: 105,
                    name: '翁庆年的六英镑',
                    url: `${prefix}/Imagine-2011/翁庆年的六英镑.mp3`,
                },
                {
                    albumId: 5,
                    songId: 106,
                    name: '秋天的老狼',
                    url: `${prefix}/Imagine-2011/秋天的老狼.mp3`,
                },
                {
                    albumId: 5,
                    songId: 107,
                    name: '1990的春天',
                    url: `${prefix}/Imagine-2011/1990的春天.mp3`,
                },
                {
                    albumId: 5,
                    songId: 108,
                    name: '结尾',
                    url: `${prefix}/Imagine-2011/Z结尾.mp3`,
                },
            ],
        },
        {
            name: '这个世界会好吗',
            year: 2011,
            albumId: 7,
            cover: '/patch/cover/这个世界会好吗.jpeg',
            songs: [
                {
                    albumId: 6,
                    songId: 109,
                    name: '妈妈',
                    url: `${prefix}/这个世界会好吗/妈妈.mp3`,
                },
                {
                    albumId: 6,
                    songId: 110,
                    name: '喀纳斯',
                    url: `${prefix}/这个世界会好吗/喀纳斯.mp3`,
                },
                {
                    albumId: 6,
                    songId: 111,
                    name: '和你在一起',
                    url: `${prefix}/这个世界会好吗/和你在一起.mp3`,
                },
                {
                    albumId: 6,
                    songId: 112,
                    name: '我们不能失去信仰',
                    url: `${prefix}/这个世界会好吗/我们不能失去信仰—献给刘艺.mp3`,
                },
                {
                    albumId: 6,
                    songId: 113,
                    name: '翁庆年的六英镑',
                    url: `${prefix}/这个世界会好吗/翁庆年的六英镑.mp3`,
                },
                {
                    albumId: 6,
                    songId: 114,
                    name: '他们',
                    url: `${prefix}/这个世界会好吗/他们.mp3`,
                },
                {
                    albumId: 6,
                    songId: 115,
                    name: '海的女儿',
                    url: `${prefix}/这个世界会好吗/海的女儿.mp3`,
                },
                {
                    albumId: 6,
                    songId: 116,
                    name: '交河',
                    url: `${prefix}/这个世界会好吗/交河.mp3`,
                },
                {
                    albumId: 6,
                    songId: 117,
                    name: '这个世界会好吗',
                    url: `${prefix}/这个世界会好吗/李志- 这个世界会好吗.mp3`,
                },
                {
                    albumId: 6,
                    songId: 118,
                    name: '人民不需要自由',
                    url: `${prefix}/这个世界会好吗/人民不需要自由.mp3`,
                },
            ],
        },
        {
            name: '108个关键词',
            year: 2013,
            albumId: 8,
            cover: `${prefix}/108个关键词/cover.png`,
            songs: [
                {
                    albumId: 7,
                    songId: 119,
                    name: '阿兰',
                    url: `${prefix}/108个关键词/阿兰.mp3`,
                },
                {
                    albumId: 7,
                    songId: 120,
                    name: '尽头',
                    url: `${prefix}/108个关键词/尽头.mp3`,
                },
                {
                    albumId: 7,
                    songId: 121,
                    name: '青春',
                    url: `${prefix}/108个关键词/青春.flac`,
                },
                {
                    albumId: 7,
                    songId: 122,
                    name: '倒影',
                    url: `${prefix}/108个关键词/倒影.mp3`,
                },
                {
                    albumId: 7,
                    songId: 123,
                    name: '忽然',
                    url: `${prefix}/108个关键词/忽然.mp3`,
                },
                {
                    albumId: 7,
                    songId: 124,
                    name: '董卓瑶',
                    url: `${prefix}/108个关键词/董卓瑶.mp3`,
                },
                {
                    albumId: 7,
                    songId: 125,
                    name: '山阴路的夏天',
                    url: `${prefix}/108个关键词/山阴路的夏天.mp3`,
                },
            ],
        },
        {
            name: '1701',
            year: 2014,
            albumId: 9,
            cover: `${prefix}/1701/cover.png`,
            songs: [
                {
                    albumId: 8,
                    name: '大象',
                    songId: 126,
                    url: `${prefix}/1701/大象.mp3`,
                },
                {
                    albumId: 8,
                    name: '鼠说',
                    songId: 127,
                    url: `${prefix}/1701/鼠说.mp3`,
                },
                {
                    albumId: 8,
                    name: '定西',
                    songId: 128,
                    url: `${prefix}/1701/定西.mp3`,
                },
                {
                    albumId: 8,
                    name: '看见',
                    songId: 129,
                    url: `${prefix}/1701/看见.mp3`,
                },
                {
                    albumId: 8,
                    name: '不多',
                    songId: 130,
                    url: `${prefix}/1701/不多.mp3`,
                },
                {
                    albumId: 8,
                    name: '热河',
                    songId: 131,
                    url: `${prefix}/1701/热河.mp3`,
                },
                {
                    albumId: 8,
                    name: '好威武支持有希望',
                    songId: 132,
                    url: `${prefix}/1701/好威武支持有希望.mp3`,
                },
                {
                    albumId: 8,
                    name: '方式',
                    songId: 133,
                    url: `${prefix}/1701/方式.mp3`,
                },
            ],
        },
        {
            name: 'F',
            year: 2014,
            albumId: 10,
            cover: `${prefix}/F/cover.png`,
            songs: [
                {
                    albumId: 9,
                    name: '寻找',
                    songId: 134,
                    url: `${prefix}/F/寻找.mp3`,
                },
                {
                    albumId: 9,
                    name: '尽头',
                    songId: 135,
                    url: `${prefix}/F/尽头.mp3`,
                },
                {
                    albumId: 9,
                    name: '门',
                    songId: 136,
                    url: `${prefix}/F/门.mp3`,
                },
                {
                    albumId: 9,
                    name: '下雨',
                    songId: 137,
                    url: `${prefix}/F/下雨.mp3`,
                },
                {
                    albumId: 9,
                    name: '山阴路的夏天',
                    songId: 138,
                    url: `${prefix}/F/山阴路的夏天.mp3`,
                },
                {
                    albumId: 9,
                    name: '女神',
                    songId: 139,
                    url: `${prefix}/F/女神.mp3`,
                },
                {
                    albumId: 9,
                    name: '你的早晨',
                    songId: 140,
                    url: `${prefix}/F/你的早晨.mp3`,
                },
                {
                    albumId: 9,
                    name: '杭州',
                    songId: 141,
                    url: `${prefix}/F/杭州.mp3`,
                },
                {
                    albumId: 9,
                    name: '日',
                    songId: 142,
                    url: `${prefix}/F/日.mp3`,
                },
            ],
        },
        {
            name: '勾三搭四',
            year: 2014,
            albumId: 11,
            cover: `${prefix}/勾三搭四/cover.png`,
            songs: [
                {
                    albumId: 10,
                    name: '和你在一起',
                    songId: 143,
                    url: `${prefix}/勾三搭四/和你在一起.mp3`,
                },
                {
                    albumId: 10,
                    name: '墙上的向日葵',
                    songId: 144,
                    url: `${prefix}/勾三搭四/墙上的向日葵.mp3`,
                },
                {
                    albumId: 10,
                    name: '铅笔',
                    songId: 145,
                    url: `${prefix}/勾三搭四/铅笔.mp3`,
                },
                {
                    albumId: 10,
                    name: '下雨',
                    songId: 146,
                    url: `${prefix}/勾三搭四/下雨.mp3`,
                },
                {
                    albumId: 10,
                    name: '被禁忌的游戏',
                    songId: 147,
                    url: `${prefix}/勾三搭四/被禁忌的游戏.mp3`,
                },
                {
                    albumId: 10,
                    name: '秋天的老狼',
                    songId: 148,
                    url: `${prefix}/勾三搭四/秋天的老狼.mp3`,
                },
                {
                    albumId: 10,
                    name: '离婚',
                    songId: 149,
                    url: `${prefix}/勾三搭四/离婚.mp3`,
                },
                {
                    albumId: 10,
                    name: '门',
                    songId: 150,
                    url: `${prefix}/勾三搭四/门.mp3`,
                },
                {
                    albumId: 10,
                    name: '斜',
                    songId: 151,
                    url: `${prefix}/勾三搭四/斜.mp3`,
                },
                {
                    albumId: 10,
                    name: '春末的南方城市',
                    songId: 152,
                    url: `${prefix}/勾三搭四/春末的南方城市.mp3`,
                },
                {
                    albumId: 10,
                    name: '黑色信封',
                    songId: 153,
                    url: `${prefix}/勾三搭四/黑色信封.mp3`,
                },
                {
                    albumId: 10,
                    name: '1990年的春天',
                    songId: 154,
                    url: `${prefix}/勾三搭四/1990年的春天.mp3`,
                },
                {
                    albumId: 10,
                    songId: 155,
                    name: '意味',
                    url: `${prefix}/勾三搭四/意味.mp3`,
                },
                {
                    albumId: 10,
                    songId: 156,
                    name: '翁庆年的六英镑',
                    url: `${prefix}/勾三搭四/翁庆年的六英镑.mp3`,
                },
                {
                    albumId: 10,
                    songId: 157,
                    name: '来了',
                    url: `${prefix}/勾三搭四/来了.mp3`,
                },
                {
                    albumId: 10,
                    songId: 158,
                    name: '妈妈',
                    url: `${prefix}/勾三搭四/妈妈.mp3`,
                },
                {
                    albumId: 10,
                    songId: 159,
                    name: '董卓瑶',
                    url: `${prefix}/勾三搭四/董卓瑶.mp3`,
                },
                {
                    albumId: 10,
                    songId: 160,
                    name: '这个世界会好吗',
                    url: `${prefix}/勾三搭四/这个世界会好吗.mp3`,
                },
                {
                    albumId: 10,
                    songId: 161,
                    name: '山阴路的夏天',
                    url: `${prefix}/勾三搭四/山阴路的夏天.mp3`,
                },
            ],
        },
        {
            name: 'i/O',
            year: 2015,
            albumId: 12,
            cover: `${prefix}/io/cover.png`,
            songs: [
                {
                    albumId: 11,
                    songId: 162,
                    name: '杭州',
                    url: `${prefix}/io/杭州.mp3`,
                },
                {
                    albumId: 11,
                    songId: 163,
                    name: '墙上的向日葵',
                    url: `${prefix}/io/墙上的向日葵.mp3`,
                },
                {
                    albumId: 11,
                    songId: 164,
                    name: '铅笔',
                    url: `${prefix}/io/铅笔.mp3`,
                },
                {
                    albumId: 11,
                    songId: 165,
                    name: '来了',
                    url: `${prefix}/io/来了.mp3`,
                },
                {
                    albumId: 11,
                    songId: 166,
                    name: '这个世界会好吗',
                    url: `${prefix}/io/这个世界会好吗.mp3`,
                },
                {
                    albumId: 11,
                    songId: 167,
                    name: '妈妈',
                    url: `${prefix}/io/妈妈.mp3`,
                },
                {
                    albumId: 11,
                    songId: 168,
                    name: '定西',
                    url: `${prefix}/io/定西.mp3`,
                },
                {
                    albumId: 11,
                    songId: 169,
                    name: '方式',
                    url: `${prefix}/io/方式.mp3`,
                },
                {
                    albumId: 11,
                    songId: 170,
                    name: '山阴路的夏天',
                    url: `${prefix}/io/山阴路的夏天.mp3`,
                },
            ],
        },
        {
            name: '看见',
            year: 2015,
            albumId: 13,
            cover: `${prefix}/看见/cover.png`,
            songs: [
                {
                    albumId: 12,
                    songId: 171,
                    name: '看见',
                    url: `${prefix}/看见/看见.mp3`,
                },
                {
                    albumId: 12,
                    songId: 172,
                    name: '黑色信封',
                    url: `${prefix}/看见/黑色信封.mp3`,
                },
                {
                    albumId: 12,
                    songId: 173,
                    name: '苍井空',
                    url: `${prefix}/看见/苍井空.mp3`,
                },
                {
                    albumId: 12,
                    songId: 174,
                    name: '春末的南方城市',
                    url: `${prefix}/看见/春末的南方城市.mp3`,
                },
                {
                    albumId: 12,
                    songId: 175,
                    name: '你离开了南京，从此没有人和我说话',
                    url: `${prefix}/看见/你离开了南京，从此没有人和我说话.mp3`,
                },
                {
                    albumId: 12,
                    songId: 176,
                    name: '下雨',
                    url: `${prefix}/看见/下雨.mp3`,
                },
                {
                    albumId: 12,
                    songId: 177,
                    name: '热河',
                    url: `${prefix}/看见/热河.mp3`,
                },
                {
                    albumId: 12,
                    songId: 178,
                    name: '董卓瑶',
                    url: `${prefix}/看见/董卓瑶.mp3`,
                },
                {
                    albumId: 12,
                    songId: 179,
                    name: '离婚',
                    url: `${prefix}/看见/离婚.mp3`,
                },
                {
                    albumId: 12,
                    songId: 180,
                    name: '梵高先生',
                    url: `${prefix}/看见/梵高先生.mp3`,
                },
            ],
        },
        {
            name: '动静',
            year: 2016,
            albumId: 14,
            cover: `${prefix}/动静/cover.png`,
            songs: [
                {
                    albumId: 13,
                    songId: 181,
                    name: '你的早晨',
                    url: `${prefix}/动静/你的早晨.mp3`,
                },
                {
                    albumId: 13,
                    songId: 182,
                    name: '普希金',
                    url: `${prefix}/动静/普希金.mp3`,
                },
                {
                    albumId: 13,
                    songId: 183,
                    name: '卡夫卡',
                    url: `${prefix}/动静/卡夫卡.mp3`,
                },
                {
                    albumId: 13,
                    songId: 184,
                    name: '和你在一起',
                    url: `${prefix}/动静/和你在一起.mp3`,
                },
                {
                    albumId: 13,
                    songId: 185,
                    name: '忽然',
                    url: `${prefix}/动静/忽然.mp3`,
                },
                {
                    albumId: 13,
                    songId: 186,
                    name: '定西',
                    url: `${prefix}/动静/定西.mp3`,
                },
                {
                    albumId: 13,
                    songId: 187,
                    name: '这个世界会好吗',
                    url: `${prefix}/动静/这个世界会好吗.mp3`,
                },
                {
                    albumId: 13,
                    songId: 188,
                    name: '墙上的向日葵',
                    url: `${prefix}/动静/墙上的向日葵.mp3`,
                },
                {
                    albumId: 13,
                    songId: 189,
                    name: '尽头',
                    url: `${prefix}/动静/尽头.mp3`,
                },
            ],
        },
        {
            name: '在每一条伤心的应天大街上',
            year: 2016,
            albumId: 15,
            cover: `${prefix}/在每一条伤心的应天大街上/cover.png`,
            songs: [
                {
                    albumId: 14,
                    songId: 190,
                    name: '在每一条伤心的应天大街上',
                    url: `${prefix}/在每一条伤心的应天大街上/在每一条伤心的应天大街上.mp3`,
                },
                {
                    albumId: 14,
                    songId: 191,
                    name: '一头偶像',
                    url: `${prefix}/在每一条伤心的应天大街上/一头偶像.mp3`,
                },
                {
                    albumId: 14,
                    songId: 192,
                    name: '克兰河',
                    url: `${prefix}/在每一条伤心的应天大街上/克兰河.mp3`,
                },
                {
                    albumId: 14,
                    songId: 193,
                    name: '死人',
                    url: `${prefix}/在每一条伤心的应天大街上/死人.mp3`,
                },
                {
                    albumId: 14,
                    songId: 194,
                    name: '一个夜晚',
                    url: `${prefix}/在每一条伤心的应天大街上/一个夜晚.mp3`,
                },
                {
                    albumId: 14,
                    songId: 195,
                    name: '哦吼',
                    url: `${prefix}/在每一条伤心的应天大街上/哦吼.mp3`,
                },
                {
                    albumId: 14,
                    songId: 196,
                    name: '彩色派对',
                    url: `${prefix}/在每一条伤心的应天大街上/彩色派对.mp3`,
                },
                {
                    albumId: 14,
                    songId: 197,
                    name: '你好明天',
                    url: `${prefix}/在每一条伤心的应天大街上/你好明天.mp3`,
                },
            ],
        },
        {
            name: '捌',
            year: 2016,
            albumId: 16,
            cover: `${prefix}/8/cover.png`,
            songs: [
                {
                    albumId: 15,
                    songId: 198,
                    name: '歌声与微笑',
                    url: `${prefix}/8/歌声与微笑.mp3`,
                },
                {
                    albumId: 15,
                    songId: 199,
                    name: '蜗牛与黄鹂鸟',
                    url: `${prefix}/8/蜗牛与黄鹂鸟.mp3`,
                },
                {
                    albumId: 15,
                    songId: 200,
                    name: '兰花草',
                    url: `${prefix}/8/兰花草.mp3`,
                },
                {
                    albumId: 15,
                    songId: 201,
                    name: '数鸭子',
                    url: `${prefix}/8/数鸭子.mp3`,
                },
                {
                    albumId: 15,
                    songId: 202,
                    name: '朋友越多越快乐',
                    url: `${prefix}/8/朋友越多越快乐.mp3`,
                },
                {
                    albumId: 15,
                    songId: 203,
                    name: 'Hey Jude',
                    url: `${prefix}/8/Hey Jude.mp3`,
                },
                {
                    albumId: 15,
                    songId: 204,
                    name: '采蘑菇的小姑娘',
                    url: `${prefix}/8/采蘑菇的小姑娘.mp3`,
                },
                {
                    albumId: 15,
                    songId: 205,
                    name: '小螺号',
                    url: `${prefix}/8/小螺号.mp3`,
                },
                {
                    albumId: 15,
                    songId: 206,
                    name: '送别',
                    url: `${prefix}/8/送别.mp3`,
                },
            ],
        },
        {
            name: '北京不插电',
            year: 2016,
            albumId: 17,
            cover: `${prefix}/北京不插电/cover.png`,
            songs: [
                {
                    albumId: 16,
                    songId: 207,
                    name: '黑色信封',
                    url: `${prefix}/北京不插电/黑色信封.mp3`,
                },
                {
                    albumId: 16,
                    songId: 208,
                    name: '鸵鸟',
                    url: `${prefix}/北京不插电/鸵鸟.mp3`,
                },
                {
                    albumId: 16,
                    songId: 209,
                    name: '大象',
                    url: `${prefix}/北京不插电/大象.mp3`,
                },
                {
                    albumId: 16,
                    songId: 210,
                    name: '定西',
                    url: `${prefix}/北京不插电/定西.mp3`,
                },
                {
                    albumId: 16,
                    songId: 211,
                    name: '这个世界会好吗',
                    url: `${prefix}/北京不插电/这个世界会好吗.mp3`,
                },
                {
                    albumId: 16,
                    songId: 212,
                    name: '结婚',
                    url: `${prefix}/北京不插电/结婚.mp3`,
                },
                {
                    albumId: 16,
                    songId: 213,
                    name: '关于郑州的记忆',
                    url: `${prefix}/北京不插电/关于郑州的记忆.mp3`,
                },
                {
                    albumId: 16,
                    songId: 214,
                    name: '杭州',
                    url: `${prefix}/北京不插电/杭州.mp3`,
                },
                {
                    albumId: 16,
                    songId: 215,
                    name: '热河',
                    url: `${prefix}/北京不插电/热河.mp3`,
                },
                {
                    albumId: 16,
                    songId: 216,
                    name: '春末的南方城市',
                    url: `${prefix}/北京不插电/春末的南方城市.mp3`,
                },
                {
                    albumId: 16,
                    songId: 217,
                    name: '鼠说',
                    url: `${prefix}/北京不插电/鼠说.mp3`,
                },
                {
                    albumId: 16,
                    songId: 218,
                    name: '山阴路的夏天',
                    url: `${prefix}/北京不插电/山阴路的夏天.mp3`,
                },
            ],
        },
        {
            name: '电声与管弦乐',
            year: 2017,
            albumId: 18,
            cover: `${prefix}/电声与管弦乐/cover.png`,
            songs: [
                {
                    albumId: 17,
                    songId: 219,
                    name: '序曲',
                    url: `${prefix}/电声与管弦乐/序曲.mp3`,
                },
                {
                    albumId: 17,
                    songId: 220,
                    name: '杭州',
                    url: `${prefix}/电声与管弦乐/杭州.mp3`,
                },
                {
                    albumId: 17,
                    songId: 221,
                    name: '尽头',
                    url: `${prefix}/电声与管弦乐/尽头.mp3`,
                },
                {
                    albumId: 17,
                    songId: 222,
                    name: '定西',
                    url: `${prefix}/电声与管弦乐/定西.mp3`,
                },
                {
                    albumId: 17,
                    songId: 223,
                    name: '春末的南方城市',
                    url: `${prefix}/电声与管弦乐/春末的南方城市.mp3`,
                },
                {
                    albumId: 17,
                    songId: 224,
                    name: '黑色信封',
                    url: `${prefix}/电声与管弦乐/黑色信封.mp3`,
                },
                {
                    albumId: 17,
                    songId: 225,
                    name: '铅笔',
                    url: `${prefix}/电声与管弦乐/铅笔.mp3`,
                },
                {
                    albumId: 17,
                    songId: 226,
                    name: '和你在一起',
                    url: `${prefix}/电声与管弦乐/和你在一起.mp3`,
                },
                {
                    albumId: 17,
                    songId: 227,
                    name: '墙上的向日葵',
                    url: `${prefix}/电声与管弦乐/墙上的向日葵.mp3`,
                },
                {
                    albumId: 17,
                    songId: 228,
                    name: '大象',
                    url: `${prefix}/电声与管弦乐/大象.mp3`,
                },
                {
                    albumId: 17,
                    songId: 229,
                    name: '门',
                    url: `${prefix}/电声与管弦乐/门.mp3`,
                },
                {
                    albumId: 17,
                    songId: 230,
                    name: '回答',
                    url: `${prefix}/电声与管弦乐/回答.mp3`,
                },
            ],
        },
        {
            name: '电声与管弦乐II',
            year: 2018,
            albumId: 19,
            cover: `${prefix}/电声与管弦乐II/cover.png`,
            songs: [
                {
                    albumId: 18,
                    songId: 231,
                    name: '相信未来序曲',
                    url: `${prefix}/电声与管弦乐II/相信未来序曲 (乐曲).mp3`,
                },
                {
                    albumId: 18,
                    songId: 232,
                    name: '一头偶像',
                    url: `${prefix}/电声与管弦乐II/一头偶像 (相信未来版).mp3`,
                },
                {
                    albumId: 18,
                    songId: 233,
                    name: '你好明天',
                    url: `${prefix}/电声与管弦乐II/你好明天 (相信未来版).mp3`,
                },
                {
                    albumId: 18,
                    songId: 234,
                    name: '寻找',
                    url: `${prefix}/电声与管弦乐II/寻找 (相信未来版).mp3`,
                },
                {
                    albumId: 18,
                    songId: 235,
                    name: '山阴路的夏天',
                    url: `${prefix}/电声与管弦乐II/山阴路的夏天 (相信未来版).mp3`,
                },
                {
                    albumId: 18,
                    songId: 236,
                    name: '哦吼',
                    url: `${prefix}/电声与管弦乐II/哦吼 (相信未来版).mp3`,
                },
                {
                    albumId: 18,
                    songId: 237,
                    name: '天空之城',
                    url: `${prefix}/电声与管弦乐II/天空之城 (相信未来版).mp3`,
                },
                {
                    albumId: 18,
                    songId: 238,
                    name: '家乡',
                    url: `${prefix}/电声与管弦乐II/家乡 (相信未来版).mp3`,
                },
                {
                    albumId: 18,
                    songId: 239,
                    name: '这个世界会好吗',
                    url: `${prefix}/电声与管弦乐II/这个世界会好吗 (相信未来版).mp3`,
                },
            ],
        },
        {
            name: '零碎',
            year: -1,
            albumId: 20,
            cover: `${prefix}/零碎/cover.png`,
            songs: [
                {
                    albumId: 18,
                    songId: 240,
                    name: '一个夜晚',
                    url: `${prefix}/零碎/一个夜晚---李志.mp3`,
                },
                {
                    albumId: 18,
                    songId: 241,
                    name: '两只HipHop山羊织毛衣',
                    url: `${prefix}/零碎/两只HipHop山羊织毛衣.mp3`,
                },
                {
                    albumId: 18,
                    songId: 242,
                    name: '妈妈',
                    url: `${prefix}/零碎/妈妈.mp3`,
                },
                {
                    albumId: 18,
                    songId: 243,
                    name: '帐号被人注销了 - 《一起摇摆》 李志团队',
                    url: `${prefix}/零碎/帐号被人注销了 - 《一起摇摆》 李志团队.mp3`,
                },
                {
                    albumId: 18,
                    songId: 244,
                    name: '撒娇 - 在劫难逃',
                    url: `${prefix}/零碎/撒娇 - 在劫难逃.mp3`,
                },
                {
                    albumId: 18,
                    songId: 245,
                    name: '撒娇 - 虎口脱险',
                    url: `${prefix}/零碎/撒娇 - 虎口脱险.mp3`,
                },
                {
                    albumId: 18,
                    songId: 246,
                    name: '李志-红色气球 (2009现场版)',
                    url: `${prefix}/零碎/李志-红色气球 (2009现场版).mp3`,
                },
                {
                    albumId: 18,
                    songId: 247,
                    name: '李志,卡列宁 - 突如其来的夏天',
                    url: `${prefix}/零碎/李志,卡列宁 - 突如其来的夏天.mp3`,
                },
                {
                    albumId: 18,
                    songId: 248,
                    name: '李志,梁颖 - 虎口脱险',
                    url: `${prefix}/零碎/李志,梁颖 - 虎口脱险.mp3`,
                },
                {
                    albumId: 18,
                    songId: 249,
                    name: '痛并快乐着',
                    url: `${prefix}/零碎/痛并快乐着.mp3`,
                },
                {
                    albumId: 18,
                    songId: 250,
                    name: '老钟 我和你在一起',
                    url: `${prefix}/零碎/老钟 我和你在一起.mp3`,
                },
                {
                    albumId: 18,
                    songId: 251,
                    name: '肖晨,陈小二 - 酒吧叙事体',
                    url: `${prefix}/零碎/肖晨,陈小二 - 酒吧叙事体.mp3`,
                },
                {
                    albumId: 18,
                    songId: 252,
                    name: '英俊的海 - 《公路之光》丨李志',
                    url: `${prefix}/零碎/英俊的海 - 《公路之光》丨李志.mp3`,
                },
                {
                    albumId: 18,
                    songId: 253,
                    name: '谁他妈没织过毛衣',
                    url: `${prefix}/零碎/谁他妈没织过毛衣.mp3`,
                },
                {
                    albumId: 18,
                    songId: 254,
                    name: '这个世界会好吗2015',
                    url: `${prefix}/零碎/这个世界会好吗2015.mp3`,
                },
                {
                    albumId: 18,
                    songId: 255,
                    name: '邵夷贝,黄昏',
                    url: `${prefix}/零碎/邵夷贝,黄昏.mp3`,
                },
                {
                    albumId: 18,
                    songId: 256,
                    name: '阿兰 2012.12.31',
                    url: `${prefix}/零碎/阿兰 2012.12.31.mp3`,
                },
                {
                    albumId: 18,
                    songId: 257,
                    name: '鹿港小镇 (Live)',
                    url: `${prefix}/零碎/鹿港小镇 (Live).mp3`,
                },
            ],
        },
    ],
};

// 随机挑 30 个 song，输出为一个数组
// const list = source.albums.reduce((acc, album) => {
//     return acc.concat(album.songs);
// }, [] as typeof source.albums[0]['songs']).sort(() => 0.5 - Math.random()).slice(0, 30);

// console.log(list);

export default source;
